# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/UnrealEngine_5.1.1
GAMEPROJECTFILE =/home/petr/Projects/UnrealEngine/BachelorThesis/BachelorThesis.uproject

TARGETS = \
	BachelorThesis-Linux-DebugGame  \
	BachelorThesis-Linux-Shipping  \
	BachelorThesis \
	BachelorThesisEditor-Linux-DebugGame  \
	BachelorThesisEditor-Linux-Shipping  \
	BachelorThesisEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend BachelorThesisEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug BachelorThesisEditor-Linux-Debug


BachelorThesis-Linux-DebugGame:
	 $(PROJECTBUILD) BachelorThesis Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BachelorThesis-Linux-Shipping:
	 $(PROJECTBUILD) BachelorThesis Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BachelorThesis:
	 $(PROJECTBUILD) BachelorThesis Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BachelorThesisEditor-Linux-DebugGame:
	 $(PROJECTBUILD) BachelorThesisEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BachelorThesisEditor-Linux-Shipping:
	 $(PROJECTBUILD) BachelorThesisEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BachelorThesisEditor:
	 $(PROJECTBUILD) BachelorThesisEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
